### PR TITLE
[#108] - Check for open time logs before sending

### PR DESCRIPTION
**Pull request by Eric115**
https://github.com/larowlan/tl/issues/108

### CODE REVIEW

**Review by larowlan — COMMENTED** [review]
looks good to me, just failing tests for old versions of php

**Comment by Eric115** [comment]
PHP 5.5 and 5.6 are EOL now, we can probably ignore the failing tests.

**Comment by larowlan** [comment]
merge master? pretty sure I nixed them in the jira work

**Comment by larowlan** [comment]
Head is now fixed if you can merge master against this @Eric115 thanks again

**Comment by larowlan** [comment]
see #118

**Pull request closed without merging**
